# Generated by Django 2.2.1 on 2019-05-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0002_auto_20190527_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='body',
            field=models.TextField(default='test'),
        ),
        migrations.AlterField(
            model_name='update',
            name='date_pub',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
