# Generated by Django 2.2.1 on 2019-05-30 07:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('updates', '0004_auto_20190529_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='update',
            name='author',
            field=models.ForeignKey(default=None, on_delete='CASCADE', to=settings.AUTH_USER_MODEL),
        ),
    ]
