# Generated by Django 2.2.1 on 2019-05-30 07:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0005_update_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='author',
            field=models.ForeignKey(on_delete='CASCADE', to=settings.AUTH_USER_MODEL),
        ),
    ]
