# Generated by Django 2.2.1 on 2019-05-30 07:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0006_auto_20190530_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='author',
            field=models.ForeignKey(blank=True, on_delete='CASCADE', to=settings.AUTH_USER_MODEL),
        ),
    ]
